version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: ecommerce_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    command: >
      sh -c "node src/database/migrate.js &&
             node src/database/seed.js &&
             node src/server.js"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
